
##Launching basic ec2 instance using yaml
- name: Ansible playbook for simple ec2 
  hosts: localhost
  tasks:
    - name:  launching ec2 instance using ansible

      amazon.aws.ec2_instance:
        key_name: test
        region: us-east-1
        instance_type: t2.micro
        image_id: ami-0e2c8caa4b6378d8c
        tags:
          Name: Ansible_server  
  
