- name: start instances
  hosts: localhost
  tasks:
    - name: start the instance
      amazon.aws.ec2_instance:
        state: started
        region: us-east-1
        tags:
          name: Ansible_server

