- name: stop instances
  hosts: localhost
  tasks:
    - name: stop the previously launched instance
      amazon.aws.ec2_instance:
        state: stopped
        region: us-east-1
        tags:
          name: Ansible_server

