- name: terminate instances
  hosts: localhost
  tasks:
    - name: terminate the instance
      amazon.aws.ec2_instance:
        state: terminated
        region: us-east-1
        tags:
          name: Ansible_server

